# Generated by Django 5.1.7 on 2025-03-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_cor_raca_alter_aluno_cartorio_uf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='ano_ou_serie',
            new_name='ano_serie',
        ),
    ]
