# Generated by Django 5.1.7 on 2025-03-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_rename_ano_ou_serie_aluno_ano_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano_serie',
            field=models.CharField(choices=[('1º ANO', '1º ANO'), ('2º ANO', '2º ANO'), ('3º ANO', '3º ANO'), ('4º ANO', '4º ANO'), ('5º ANO', '5º ANO')], max_length=30),
        ),
    ]
