# Generated by Django 5.1.6 on 2025-03-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_aluno_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ano_rematricula',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
