# Generated by Django 5.1.6 on 2025-03-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_aluno_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2)),
                ('serie', models.CharField(max_length=50)),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas', to='alunos.aluno')),
            ],
        ),
    ]
