# Generated by Django 5.1.6 on 2025-03-30 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_professor_aluno_professor_turma_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='max_alunos',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alunos.professor'),
            preserve_default=False,
        ),
    ]
