# Generated by Django 5.1.6 on 2025-03-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_turma_max_alunos_alter_turma_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='serie',
            field=models.CharField(choices=[('1º ANO', '1º ANO'), ('2º ANO', '2º ANO'), ('3º ANO', '3º ANO'), ('4º ANO', '4º ANO'), ('5º ANO', '5º ANO')], max_length=50),
        ),
    ]
