# Generated by Django 5.1.6 on 2025-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
